version: "3.9"

services:
  web:
    build: .
    container_name: tricot-tout-petits-php
    ports:
      - "8080:80"
    # En dev : monter le dossier courant dans le conteneur
    volumes:
      - .:/var/www/html
    restart: unless-stopped


